### ISSUE TITLE
consider adding  serialization middleware

### ISSUE THREAD

**Issue by sandys** [encode/hostedapi#56]
hi,
This is very important for production usecases especially around performance or migrating apis (from Flask for e.g.) that service mobile apps that are already in the wild 

gzipped json or msgpack responses - (similar issue on fastapi side https://github.com/tiangolo/fastapi/issues/521 or https://fastapi.tiangolo.com/tutorial/custom-request-and-route/#create-a-custom-gziprequest-class) . 

the api should respond to mimetype requests for serialization. It makes a significant difference in high traffic and large data transfer usecases. 

The default behavior doesnt change - however the api should be able to honor requests (either GET or POST) that ask for a certain mimetype (e.g. `application/msgpack `). I'm not sure if chunked responses need a certain way to do it ...or if it is even possible without a change to starlette.

**Comment by florimondmanca** [comment]
@sandys Not sure personally how relevant this is to HostedAPI, but I left a comment tiangolo/fastapi#521, basically stating that this could be a good candidate for a new ASGI middleware shipped with Starlette.

**Comment by sandys** [comment]
Thanks for your comment. Im not completely sure if Starlette already has
the capability built in somehow (and that i missed). That's the reason I
filed it here.

**Comment by florimondmanca** [comment]
Sure, but this repository is that of an example production Starlette app, not Starlette itself. :-) I suggest discussion continues on https://github.com/tiangolo/fastapi/issues/521 and perhaps an issue should be opened on Starlette.

**Comment by tomchristie** [comment]
> Sure, but this repository is that of an example production Starlette app, not Starlette itself.

Indeed. Not relevant to this repo. 😃

Starlette does include a GZip middleware, for transparently adding GZip on top of responses. https://github.com/encode/starlette/blob/master/starlette/middleware/gzip.py

Response serialization is perfectly possible by implementing custom response classes, though I'd almost certainly push for any support there to be third-party, rather than built in directly.

**Comment by florimondmanca** [comment]
FYI, I just pushed [msgpack-asgi](https://github.com/florimondmanca/msgpack-asgi). `MessagePackMiddleware` does exacty what @sandys mentioned:

> The default behavior doesnt change - however the api should be able to honor requests (either GET or POST) that ask for a certain mimetype (e.g. `application/msgpack `).

Not yet released to PyPI, but probably soon!
