### ISSUE TITLE
Use pre-commit

### ISSUE THREAD

**Issue by devsetgo** [encode/hostedapi#79]
First, love this example. It has helped understand some parts of Starlette.

I would suggest using [pre-commit](https://pre-commit.com/) to maintain code quality standards such as black. For example below is what I have in my own .pre-commit-config.yaml. This would eliminate the need to run a script for black or other code standard enforcement.

Black is run (config is in a setup.cfg), fix-encoding-pragma adds "# -*- coding: utf-8 -*- to the top of python files", trailing-whitespace "This hook trims trailing whitespace", and python-safety-dependencies-check to check for security vulnerabilities.

repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: fix-encoding-pragma
      - id: trailing-whitespace

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check

**Comment by tomchristie** [comment]
Thanks for the recommendation! 😀
Our CI currently enforces black and other linting, and I'm happy with the workflow, so going to pass on this.
